'use client';

import { useAuth } from '@/contexts/AuthContext';
import AppShell from '@/components/AppShell';
import LoginPage from '@/components/LoginPage';
import { useState, useEffect, useCallback } from 'react';
import { Dumbbell, MessageSquare, Calendar } from 'lucide-react';
import { useRouter } from 'next/navigation';

const DAY_NAMES = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

export default function WorkoutPage() {
    const { user, loading } = useAuth();
    const [schedule, setSchedule] = useState(null);
    const [loadingSchedule, setLoadingSchedule] = useState(true);
    const [flippedIdx, setFlippedIdx] = useState(null);
    const router = useRouter();

    const fetchSchedule = useCallback(async () => {
        if (!user) return;
        try {
            const syncRes = await fetch('/api/auth/sync', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    firebaseUid: user.uid,
                    email: user.email,
                    fullName: user.displayName,
                }),
            });
            const syncData = await syncRes.json();
            if (!syncData.user?.id) return;

            const res = await fetch(`/api/workout?userId=${syncData.user.id}`);
            const data = await res.json();
            if (data.schedule) {
                setSchedule(data.schedule);
            }
        } catch (e) {
            console.error('Failed to load schedule:', e);
        } finally {
            setLoadingSchedule(false);
        }
    }, [user]);

    useEffect(() => {
        if (user) fetchSchedule();
    }, [user, fetchSchedule]);

    if (loading) return null;
    if (!user) return <LoginPage />;

    const workouts = schedule?.schedule || [];
    const sortedWorkouts = [...workouts].sort((a, b) => a.dayOfWeek - b.dayOfWeek);

    const handleFlip = (i) => setFlippedIdx(flippedIdx === i ? null : i);

    return (
        <AppShell>
            <div className="memories-page">
                <div className="memories-header" style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                    <Dumbbell size={24} color="var(--color-accent)" strokeWidth={2} />
                    <h2 className="memories-title" style={{ margin: 0 }}>Workout</h2>
                    {schedule && (
                        <span className="memories-count" style={{ margin: 0, marginTop: '2px' }}>
                            Updated {new Date(schedule.lastUpdated).toLocaleDateString()}
                        </span>
                    )}
                </div>
                <p className="memories-subtitle" style={{ marginBottom: 'var(--space-6)' }}>
                    Your schedule generated by Cesy · tap cards to explore
                </p>

                {loadingSchedule ? (
                    <div className="memories-loading">
                        <div className="spinner" style={{ width: 24, height: 24 }} />
                        <span>Loading schedule...</span>
                    </div>
                ) : sortedWorkouts.length > 0 ? (
                    <div className="memory-grid">
                        {sortedWorkouts.map((workout, i) => {
                            const isToday = new Date().getDay() === workout.dayOfWeek;
                            const isFlipped = flippedIdx === i;
                            const chatPrompt = `I'm about to do my ${workout.workoutType} workout — give me tips, key form cues, and some motivation!`;
                            const chatUrl = `/?q=${encodeURIComponent(chatPrompt)}`;
                            const fallbackNote = `${workout.workoutType} day.`;
                            const relative = isToday ? 'Today' : (DAY_NAMES[workout.dayOfWeek] || 'Unknown');

                            return (
                                <div
                                    key={i}
                                    className={`flip-card${isFlipped ? ' flipped' : ''}`}
                                    onClick={() => handleFlip(i)}
                                    style={{ minHeight: '100px' }}
                                >
                                    <div className="flip-card-inner">
                                        {/* FRONT */}
                                        <div className="flip-card-front">
                                            <div
                                                className="memory-card"
                                                style={{
                                                    height: '100%', boxSizing: 'border-box',
                                                    ...(isToday ? { borderColor: 'var(--color-accent)', borderWidth: '1px', borderStyle: 'solid' } : {}),
                                                }}
                                            >
                                                <div style={{ flex: 1 }}>
                                                    <div style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '0.8rem', color: isToday ? 'var(--color-accent)' : undefined, marginBottom: '6px' }}>
                                                        <Dumbbell size={14} />
                                                        <span style={{ fontWeight: isToday ? 600 : 400 }}>{relative}</span>
                                                    </div>
                                                    <p className="memory-content" style={{ fontSize: '1rem', fontWeight: 500 }}>{workout.workoutType}</p>
                                                    <div style={{ display: 'flex', gap: '8px', fontSize: '0.75rem', opacity: 0.6, marginTop: '4px' }}>
                                                        {workout.duration && <span>{workout.duration} min</span>}
                                                        {workout.equipment?.length > 0 && <span>• {Array.isArray(workout.equipment) ? workout.equipment.join(', ') : workout.equipment}</span>}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        {/* BACK */}
                                        <div className="flip-card-back">
                                            <span className="flip-card-back-label">
                                                {isToday ? "Today's session" : DAY_NAMES[workout.dayOfWeek]}
                                            </span>
                                            <p className="flip-card-back-note">
                                                {workout.note || fallbackNote}
                                            </p>
                                            <a
                                                href={chatUrl}
                                                className="flip-chat-btn"
                                                onClick={(e) => e.stopPropagation()}
                                            >
                                                <MessageSquare size={14} /> Chat
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            );
                        })}
                    </div>
                ) : (
                    <div className="memories-empty">
                        <Dumbbell size={48} color="var(--color-accent)" strokeWidth={1} style={{ opacity: 0.3 }} />
                        <p>No Schedule Yet</p>
                        <p style={{ opacity: 0.6, fontSize: '0.8rem', textAlign: 'center', maxWidth: '300px' }}>
                            Ask Cesy to create a workout schedule for you in the chat.
                        </p>
                        <a href="/" className="btn btn-primary" style={{ marginTop: '1rem', display: 'inline-flex', gap: '8px' }}>
                            <MessageSquare size={18} /> Go to Chat
                        </a>
                    </div>
                )}
            </div>
        </AppShell>
    );
}
